version: "3.5"
services:
    php:
        image: jahirraihan/laravel-kubernetes:laravel-10-v1.0
        restart: always
        ports:
            - 8000:80
        environment:
            - APP_KEY="base64:TaENrFs0JGaXepfM4Wy7GKRs2M54Vbw9U4AUXrJdkY0="
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_PORT=3306
            - DB_HOST=mysql
            - DB_DATABASE
            - DB_USERNAME
            - DB_PASSWORD
    mysql:
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
